### ISSUE TITLE
insertId broken on Android (INSERT statement)

### ISSUE THREAD

**Issue by maarcosd** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#18]
UPDATE #2 5-May by @chbrody, title changed again: 

It is entirely possible to get the proper insertId in response to the INSERT statement by using executeInsert() on a compiled statement. However, to get the number of rows affected requires executeUpdateDelete(), which is only supported for Android API 11+, and I had trouble getting this to work on a test version so I would like to defer the fix for rowsAffected to another issue.

UPDATED 5-May by @chbrody with new title: rowsAffected

From automatic testing (see #4) it is determined that the insertId & rowsAffected fields in the response object are broken for the Android version for INSERT, UPDATE, and DELETE. The solution is to use myDb.compileStatement() for any of these statements and then run executeInsert() or executeUpdateDelete() on the compiled statement and use the return result. Doc links: http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html and http://developer.android.com/reference/android/database/sqlite/SQLiteStatement.html

The first 3 comments are related to the issue as reported by @marcosd. This issue will be solved with a test-driven approach, time permitting.

Original title: insertId returns null

Original report by @marcosd:

```
db.transaction(function(tx) {
    tx.executeSql('INSERT INTO tabletest (column1, column3, column3) '
                + 'VALUES (?,?,?)', [1,1,1], function(tx, res) { 
        alert(res.insertId);
    });
}, errorDB);
```

This code I was using with HTML5 SQL API and it was working fine, but now the alert returns null. Is it a bug or getting the generated id is different with this plugin?

Cheers

**Comment by brody2consult** [comment]
> This code I was using with HTML5 SQL API and it was working fine, but now the alert returns null. Is it a bug or getting the generated id is different with this plugin?

I will assume that this is also the Android version. AFAIK you should
be able to get a valid value for res.insertId in the result from an
INSERT SQL statement. I took a quick look at the CoffeeScript version
and this should be the case. So far, this looks like a bug but I
cannot be sure without seeing the entire program.

I will try to make a simple test suite this weekend (see #4) so we can
get the verification under control (make it more repeatable), then it
should be possible to submit a test case to reproduce each problem
that we are finding. Unless this one is really urgent for you, my plan
is to make a simple test case before investigating this one.

**Comment by maarcosd** [comment]
On the file `SQLitePlugin.java`, at the line 188 (where the query is executed) there is a cursor that, on the following line, is passed to the function `processResults`, which reads all the lines of the cursor. I don't develop in Java/Android, but as I could see, the cursor comes empty when a INSERT query is executed, so the function `processResults` returns nothing (it returns a JSON object equal to `[]`) to the Javascript, which executes the callback (on the function declared on the line 151 of the file `SQLitePlugin.js`). So from this, I could conclude that the problem might be on the Java code, which should send to Javascript the inserted ID. If I am right, I hope I can give you a clue of how to fix it.

I tried solve this issue on my Javascript getting the last id in the callback function like this:

```
db.transaction(function(tx) {
    tx.executeSql('CREATE TABLE IF NOT EXISTS tabletest (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, column1, column2, column3)');
    tx.executeSql('INSERT INTO tabletest (column1, column2, column3) VALUES (?,?,?)', [1,2,3], function(tx, res) {
        alert('insert');
        tx.executeSql('SELECT * FROM SQLITE_SEQUENCE WHERE name = "tabletest"', [], function(tx, res) {
            alert('lastid');
        }, errorDB);
    }, errorDB);
}, errorDB);
```

But the function that should alert "lastid" wasn't called, neither the error function (I tried doing this with HTML5 SQL API, and it worked, so it might be a bug, I don't know).

Anyway, to solve it I did this:

```
db.transaction(function(tx) {
    tx.executeSql('CREATE TABLE IF NOT EXISTS tabletest (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, column1, column2, column3)');
    tx.executeSql('INSERT INTO tabletest (column1, column2, column3) VALUES (?,?,?)', [1,2,3], function(tx, res) {}, errorDB);
    tx.executeSql('SELECT * FROM SQLITE_SEQUENCE WHERE name = "tabletest"', [], function(tx, res) {
        alert(res.rows.item(0).seq);
    }, errorDB);
}, errorDB);
```

And now I am finally getting the id.

**Comment by brody2consult** [comment]
hi @marcosd first the nested transaction is really tricky. I have documented it in the README but maybe I should try to make it a little more clear. I suspect you are right that the Java code is not returning the ID properly, I am happy if you post a fix or a patch. I plan to spend some time this weekend to look at this problem and add some testing.

**Comment by brody2consult** [comment]
OK I have done some reading and it looks like the compiled INSERT statement must be binded to each parameter in the params array, if present, before it can executed with expectation of meaningful results. It will take me some time to do this right so I leave this task for another day, probably sometime next weekend.

**Comment by brody2consult** [comment]
@marcos can you verify if this is fixed for you?

**Comment by viviosoft** [comment]
Thanks for the quick turnaround Chris.  I tried the new release and for some reason the inserts aren't working for the large datasets we worked on the other day (issue #37)?  It's inserting blank records.  I do however get the correct number of rows (2087) but all records were NULL.  The database, tables and rows are all getting created in their proper locations as expected. 

To verified this wasn't something I may have done wrong. I went back to using issue #36 (stable code) and testing the inserts with that code and everything inserted fine.  Then went and used the new #18/#38 release and nothing inserted but empty datasets.

I know you probably did your own testing and it worked for you.  I tested using Android 4.0 SDK 11 Emulator and physical device Android 4.0 Razr.  If it will help to do your testing using my code and datasets I can send you something to your private email.  I'll send you the locations to the web services and the code that creates and inserts the code into the database.  Hope this helps.

**Comment by brody2consult** [comment]
Hi @viviosoft I did very quick testing but maybe not enough. I had actually seen a very similar problem yesterday when I tried to run it with SQLCipher for Android so I will test it again and keep you posted with the results.

I will let you know if I need your code and datasets, I do not need this yet. Anyway my private e-mail is chris dot brody at gmail dot com

Also if we really get this working well for you, can I use your app as a sample?

**Comment by brody2consult** [comment]
Hi @viviosoft I just reproduced a problem with getting NULL data, my fault. I will work on this and keep you posted, my bad.

**Comment by viviosoft** [comment]
No problem - Thank you.

**Comment by brody2consult** [comment]
@viviosoft the problem should now be fixed can you verify this again?

**Comment by viviosoft** [comment]
It is working as expected.  Database is getting populated and id of last inserted record ID is getting returned.  Thanks a bunch!

**Comment by brody2consult** [comment]
Glad to hear!
