### ISSUE TITLE
problem with android

### ISSUE THREAD

**Issue by davidec** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#25]
Hi, I try this plugin with my talbe android 3.2.1 
I run the www-test under my tablet with a phonegap project (ver.1.7), the test star but it stop al first step 
"1. Running db transaction test".... nothing happen then this step
I try to write some test code but It 's seem don't work

Davide C

**Comment by brody2consult** [comment]
Please check that you have registered the plugin properly in
Android/res/xml/plugins.xml

On Tue, May 8, 2012 at 6:34 PM, davidec
reply@reply.github.com
wrote:

**Comment by juniovitorino** [comment]
@chbrody have some step-by-step how setup SQLitePlugin on Android as the iOS?

**Comment by brody2consult** [comment]
Installation instructions and test program added. @davidec can you please report whether or not it works so I can close this one?

**Comment by davidec** [comment]
HI,
I try 3 month ago, I don't remember single step, I remember that It 's no work
If you confirm that It work with android In these days I can re-test

**Comment by brody2consult** [comment]
On Tue, Jul 24, 2012 at 11:50 AM, davidec
reply@reply.github.com
wrote:

> HI,
> I try 3 month ago, I don't remember single step, I remember that It 's no work
> If you confirm that It work with android In these days I can re-test
> Yes it will work with Android and I have made some updates to work for
> Cordova 1.9.0. I suggest you try the small test program after the
> Android installation instructions and report whether or not it works.
> I will try to get it working with Cordova 2.0 soon.
