### ISSUE TITLE
'Undefined is not a function' error if error callback for transaction is not supplied 

### ISSUE THREAD

**Issue by yul** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#26]
I know that in the readme all transactions have error callbacks, but I didn't need it and didn't want to stream messages to console (they say Apple don't like console messages), so I just skipped this parameter, which have led to this error message. I think it worth mentioning in readme, or handle missing callback in code.

**Comment by brody2consult** [comment]
This should already be fixed by the enhancements from @ef4.
