### ISSUE TITLE
setPath is not the correct location always

### ISSUE THREAD

**Issue by steveoh** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#28]
We are trying to use a FileTransfer to download a sqlite database and use this plugin to read it.

I was able to loop through everything in data/data/package and it was not placed there.

Things downloaded with FileTransfer are placed in in mnt/sdcard which is accessible from Environment.getExternalStorageDirectory().getAbsolutePath();

**Comment by steveoh** [comment]
https://github.com/steveoh/Cordova-SQLitePlugin/commit/3a414057f186ccfcede2e120e15977739e7db556

**Comment by brody2consult** [comment]
Can you put that in a pull request?

On Sun, Jun 17, 2012 at 5:51 AM, steve
reply@reply.github.com
wrote:

**Comment by steveoh** [comment]
I think i did. its in the link above.
