### ISSUE TITLE
database not getting saved in the correct location

### ISSUE THREAD

**Issue by viviosoft** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#36]
The database file is not being saved to the correct location and the filename is not what I would expect.  This is happing in the lastest version of Cordova-SQLitePlgin.  I'm using the example unit test provided in the zip/tar package.  I'm running the application on the emulator.  Everything seems to work fine. However, the database is NOT getting saved under /data/data/com.phonegap.demo/databases/ ?

It gets saved a level below... /data/data/com.phonegap.demo/  and move over, the name of the file that gets created is strange... it starts with app_  so the filename that current'y gets created is app_databaseDatabase

I would expect the name to be just Database (which is in the example) and be placed under the Databases/ folder as indicated in the documentation.  I'm running Android SDK Version 11 / Android 4.0

The reason for my wanting the file in the correct location is that I want to be able to get at the data using the native Java approach in some cases.  No changes to the source code have been made at this point.

Thanks for any help that one can provide me.

Damian

**Comment by brody2consult** [comment]
Damian @viviosoft I just made a fix and checked that the location is correct using adb shell can you please test it and report if it works for you?

**Comment by brody2consult** [comment]
A couple useful links:
- http://androidforums.com/application-development/176793-how-can-i-view-android-emulators-file-system.html
- http://stackoverflow.com/questions/1510840/where-does-android-emulator-store-sqlite-database

**Comment by viviosoft** [comment]
It is now in fact saving in the proper location with the proper name.  Thank you.

Tested with Cordova 2.0.0 & 1.9.0 / Android 4.0 / SDK 11

**Comment by brody2consult** [comment]
Thanks, happy to hear.
