### ISSUE TITLE
Inserting multiple records into table

### ISSUE THREAD

**Issue by viviosoft** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#37]
Chris -

Is there a place to ask general questions for this plugin?  Here's what I need to know but I'm sure this isn't the place to ask it.  

Is there an example that discribes how to send multiple inserts (1000's) of records using this plugin?  I want to send an array of records to insert into a table using this plugin... can this be done?  Thanks again.

**Comment by viviosoft** [comment]
I've create a solution. However, it takes about 2 mins to insert 2000+ records.   Here's what I've come up with... I was hoping there was maybe a better way?

```
    AVDB = window.sqlitePlugin.openDatabase("vsdatabase", "mobile database", 200000);

    function GetResults(func) {
        $.mobile.showPageLoadingMsg("b", "Updating Records, Please Wait...", true);
        $.getJSON("http://www.domain.com/projects/vs/mobile/services/android-stores-list.php", null, func)
            .success(function(){
                console.log("Completed");
                $.mobile.hidePageLoadingMsg();
            });
    }

    $(function () {
        GetResults(function (response) {
            //iterate through the response rows
            $.each(response, function (key, val) {
                AVDB.transaction(function (tx) {
                    tx.executeSql('INSERT INTO stores (sName) VALUES (?)',
                        [val.sName]
                    );
                });
            });
        });
```

**Comment by brody2consult** [comment]
The solution is OK but not very efficient since the transaction between Javascript and the Android Java. One improvement is to execute multiple SQL statements in a single transaction, for example:

```
AVDB.transaction(function (tx) {
    //iterate through the response rows
    $.each(response, function (key, val) {
        tx.executeSql('INSERT INTO stores (sName) VALUES (?)', [val.sName]);
    });
});
```

It should run faster but be careful: too many SQL statements in the same DB transaction will likely block your app.

The next improvement is to do some chunking, so that each DB transaction will execute a certain limit of SQL statements. You may have to do some callback to asynchronously wait for each DB transaction to finish to keep your app from blocking.

Please can you report if you get better results by batching and/or chunking and I will use your results in the documentation.

Chris

**Comment by viviosoft** [comment]
Chris -

Your modified approach did improve performance.  Testing on Emulator Android 4.0 / SDK 11: Using a stop watch, I timed both methods.  The first method took approximately 1 min 40 sec. to insert 2087 records.  Your modified method took only 40 sec. to insert 2087.  

Testing on physical device - Android Razr v4.0.3 using 4G - Testing first method took 1 min 02 sec to insert 2087 records. Second method took 10 secs. Vast improvement!  I'm sure others may experience different speed results.

Thanks for your help on this.  I'll probability revisit this issue but I think the improvements made are enough to satisfy my client and me.

Here the source in it's entirety.

*\* PHP Service -- service.php

// Need to allow for external access outside the local domain.  This block will allow for this.
header('Cache-Control: no-cache, must-revalidate');
header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
header('Access-Control-Allow-Origin: *');
header('content-type: text/plain; charset=utf-8');

// Will need to connect to database
require_once("../../include/initialize.php");

// Select data from database
$sql = "select \* from stores";
$results = mysql_query($sql) or die(mysql_error());

// Create empty array for use to use.
$return_arr = array();

// Build array object
while ($row = mysql_fetch_array($results, MYSQL_ASSOC)) {

```
$row_array['id'] = $row['id'];
$row_array['cId'] = $row['cId'];
$row_array['sName'] = $row['sName'];

array_push( $return_arr, $row_array );
```

}

// Sleep to allow build of array.
sleep(1);

/\* Toss back results as json encoded array. */
echo json_encode($return_arr);

*\* End PHP **

*\* JavaScript - **

```
    // Open / Connect to database to insert values from jSON service
    AVDB = window.sqlitePlugin.openDatabase("database", "mobile database", 200000);

    // Call Service function
    $(function () {
        GetServiceResults(function (response) {
            AVDB.transaction(function (tx) {
                //iterate through the response rows
                $.each(response, function (key, val) {
                    tx.executeSql('INSERT INTO stores (id, cId, sName) VALUES (?, ?, ?)',
                        [ val.id, val.cId, val.sName ]);
                });
            });
        });
    });

    // Connect to service and pass back jSON results
    function GetServiceResults(func) {
        $.mobile.showPageLoadingMsg("b", "Updating, Please Wait...", true);
        $.getJSON("http://www.domain.com/mobile/services/service.php", null, func)
            .success(function(){
                console.log("Update Completed");
                $.mobile.hidePageLoadingMsg();
            });
    }
```

**\* End JavaScript ***

**Comment by brody2consult** [comment]
Woah awesome, this can help me improve the documentation someday. The mailing list could be interesting, depending on which way this project goes in the future.
