### ISSUE TITLE
JSONString Namespace Problem with "incubator" Cordova repo 

### ISSUE THREAD

**Issue by LouAlicegary** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#39]
I use the Cordoba incubator repo at git.apache.org/incubator-cordova-ios.git, as I'm sure many others do, and I had a couple of problems to fix before I could get the plugin to work.
#1) The big one: When building, I'd always get a warning at line 228 of the SQLitePlugin.m file. After a couple hours of searching around, I stumbled on the solution of changing "JSONString" to "cdvjk_JSONString" on that line, which got rid of the error. I assume something was changed with the JSONKIT that ships with Cordova, but I'm not certain...
#2) For users who aren't overly familiar with Objective C and concepts like Automatic Reference Counting (ARC), it's worth mentioning in the README that it should be disabled in order to avoid a multitude of errors upon compilation. Unless this is done (and I don't believe it is by default, as I experienced this error at first), newer users may struggle to understand what is going on.***

Thanks for all the hard work, developers. I'm glad there's a solution to the HTML5 storage problem on iOS!

***[Any users that are getting ARC errors, click on your app name at the top of the left-hand column in the Project Navigator, then click on the app name under "Targets," click on the "Build Phases" tab, and then double-click on the SQLitePlugin.m file under "Compile Sources" and add a "-fno-objc-arc" compiler flag to that entry.]

**Comment by brody2consult** [comment]
Thank you @LouAlicegary, I have documented these problems in the README. After 2.1.0 is released then I will checkin the patch to SQLitePlugin.m. This is due to [Apache Cordova CB-1000](https://issues.apache.org/jira/browse/CB-1000).

**Comment by brody2consult** [comment]
Problem with JSONString is now fixed for good, and dealing with ARC is documented better in README
