### ISSUE TITLE
instance method '-cdvjk_JSONString' not found

### ISSUE THREAD

**Issue by nadl84** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#40]
Hi,

I'm getting this warning when compiling:

SQLitePlugin.m:231:43: warning: instance method '-cdvjk_JSONString' not found (return type defaults to 'id')
        [self respond:callback withString:[resultSet cdvjk_JSONString] withType:@"success"];

Any ideas ?

**Comment by brody2consult** [comment]
Which version of Cordova are you using? The patch to use cdvjk_JSONString
only applies to the version from GIT until Cordova 2.1 is released.

**Comment by nadl84** [comment]
I'm using Cordova 2.0. Do I have to keep JSONString instead of cdvjk_JSONString ?

**Comment by brody2consult** [comment]
> I'm using Cordova 2.0. Do I have to keep JSONString instead of
> cdvjk_JSONString ?
> Yes.

**Comment by nadl84** [comment]
No more warnings. Thanks a LOT! :-)

**Comment by philmitchell** [comment]
In a similar vein, I'm getting: _Instance method '-JSONString' not found (return type defaults to 'id')_
I'm using Cordova 2.1 incubating src, because I need the fixes for IOS6. Should I add the cdvjk_ prefix?

**Comment by brody2consult** [comment]
yes

**Comment by philmitchell** [comment]
Got it ... Thanks, Chris!!

**Comment by brody2consult** [comment]
> I'm using Cordova 2.1 incubating src, because I need the fixes for IOS6.
> Should I add the cdvjk_ prefix?

Cordova official release is now 2.1, this will be standard in the source.

Chris

**Comment by brody2consult** [comment]
Fixed and closed.

**Comment by hainc08** [comment]
change 
[NSString *jsStatement = [NSString stringWithFormat:@"window.plugins.pushNotification.notificationCallback(%@);", [userInfo cdvjk_JSONString]];]
--> 
NSString *jsStatement = [NSString stringWithFormat:@"window.plugins.pushNotification.notificationCallback(%@);", [userInfo JSONString]];
