### ISSUE TITLE
Type FIELD_TYPE_BLOB cannot be resolved or is not a field	SQLitePlugin.java

### ISSUE THREAD

**Issue by churcho** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#41]
I am getting this error "Description    Resource    Path    Location    Type
FIELD_TYPE_BLOB cannot be resolved or is not a field    SQLitePlugin.java   /PhoneGap-helloworld/src/com/phonegap/plugin/sqlitePlugin   line 250    Java Problem
"

I have tried to set up the plugin as directed in your ReadMe. What is it that I am doing wrong? I am on Windows 7, running eclipse for Android Development.

Thanks for a great tool.

**Comment by churcho** [comment]
Forgot to read the lines 

<code>
// for old Android SDK remove lines from HERE:
                        if(android.os.Build.VERSION.SDK_INT >= 11)
</code>

Deleted the designated lines and now its compiling.

**Comment by brody2consult** [comment]
> Deleted the designated lines and now its compiling.

Good to hear. Documentation could be better, much better.

**Comment by churcho** [comment]
How can I pm you some requests. I need a few pointers on how to use the plugin. Thanks.

**Comment by brody2consult** [comment]
> How can I pm you some requests. I need a few pointers on how to use the
> plugin. Thanks.
> chris.brody@gmail.com I can probably help you sometime later, perhaps
> over the weekend.
