### ISSUE TITLE
Build time with SQLCipher

### ISSUE THREAD

**Issue by nadl84** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#42]
Hi,

I've modified the default cordova iOS template to add SQLite and SQLCipher dependencies. I use cordova command line tools to copy the template for each one of my apps, add my web source code and build it using:

xcodebuild -project /Path/to/my/project/myproject.xcodeproj -target myproject -configuration Release -sdk iphoneos5.1 build CONFIGURATION_BUILD_DIR=/Path/to/my/project/build

The main issue is that i'm getting really slow build times (Up to 5 minutes). I think SQLCipher dependencies are a bottleneck.

Is there any workaround to improve build times ?

Thanks in advance,

**Comment by brody2consult** [comment]
> Is there any workaround to improve build times ?

Both rebuilding SQLCipher and rebuilding openssl contribute to the
slow build times. You should be able to include these dependencies as
library dependencies and not project dependencies. I can investigate
this sometime later.

To be honest, I do not really like having 3 library project
dependencies between SQLCipher, openssl, and Cordova and already have
some ideas for improvement. More on this later.

**Comment by nadl84** [comment]
I'll be waiting for the improvements then. Thank you for the work already done :-)

**Comment by brody2consult** [comment]
SQLCipher is now supported in https://github.com/litehelpers/Cordova-sqlcipher-adapter
