### ISSUE TITLE
Android SQLCipher: Couldn't load stlport_shared

### ISSUE THREAD

**Issue by nadl84** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#43]
Hi,

I'm trying to get my android app to work with SQLCipher. I followed the steps in: http://mobileapphelp.blogspot.com/2012/08/trying-sqlcipher-with-cordova.html

This exception is thrown when i'm trying to launch the app:

E/AndroidRuntime( 2328): FATAL EXCEPTION: main
E/AndroidRuntime( 2328): java.lang.UnsatisfiedLinkError: Couldn't load stlport_shared: findLibrary returned null
E/AndroidRuntime( 2328):    at java.lang.Runtime.loadLibrary(Runtime.java:365)
E/AndroidRuntime( 2328):    at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime( 2328):    at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:142)
E/AndroidRuntime( 2328):    at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:137)
E/AndroidRuntime( 2328):    at com.phonegap.plugin.sqlitePlugin.SQLitePlugin.openDatabase(SQLitePlugin.java:144)
E/AndroidRuntime( 2328):    at com.phonegap.plugin.sqlitePlugin.SQLitePlugin.execute(SQLitePlugin.java:57)
E/AndroidRuntime( 2328):    at org.apache.cordova.api.PluginManager.exec(PluginManager.java:218)
E/AndroidRuntime( 2328):    at org.apache.cordova.CordovaChromeClient.onJsPrompt(CordovaChromeClient.java:207)
E/AndroidRuntime( 2328):    at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:600)
E/AndroidRuntime( 2328):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2328):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2328):    at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime( 2328):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2328):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2328):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime( 2328):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime( 2328):    at dalvik.system.NativeStart.main(Native Method)

Any ideas ?

Thanks in advance,

**Comment by nadl84** [comment]
It was an emulator problem. It should be created using:

android create avd -n android7 -t 7 --abi armeabi-v7a

**Comment by brody2consult** [comment]
Please can you report which Andriod API level number, if you see this on
the simulator, and if so then which version of the Android is in the
simulator?

I can take a further look after a day or so.

Chris

**Comment by brody2consult** [comment]
Thanks, I will look after a day or so.
