### ISSUE TITLE
Phonegap.exec and cordova.exec [cleanup for Android]

### ISSUE THREAD

**Issue by applecrosstwist** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#44]
With the latest version of cordova i was experiencing trouble with the "return PhoneGap.exec(..." Statements in the SQLitePlugin.js

What fixed it for me was replacing "return PhoneGap.exec" with "cordova.exec". Removing the "return" that is.

You might want to put this into the Instructions.

**Comment by brody2consult** [comment]
I assume you mean the Android version since the iOS version no longer uses PhoneGap.exec(). It was working as-is with PhoneGap.exec() on Cordova 2.0 and 2.1. I would like to clean up the code so I will leave this issue open for now.

**Comment by brody2consult** [comment]
Android version has moved to [brodyspark / PhoneGap-sqlitePlugin-Android](https://github.com/brodyspark/PhoneGap-sqlitePlugin-Android), this issue is now fixed in the new version.
