### ISSUE TITLE
Unit tests: a statement with no error handler failed

### ISSUE THREAD

**Issue by mozey** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#46]
Had to replace

equal(err.message, "a statement with no error handler failed");

with

equal(err.message.match("a statement with no error handler failed").length, 1);

before the unit tests would pass on iOS 6 iPhone simulator with Cordova 2.1.0

**Comment by brody2consult** [comment]
> Had to replace
> [...]

To be fixed but probably in a different way, simply to check that in
fact the err.message is populated alright.
