### ISSUE TITLE
Example does not run on Samsung Galaxy Tab 2 with Android 3.2

### ISSUE THREAD

**Issue by dust10** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#48]
We are hitting an issue where tables are not being created in the database created with the sqlite plugin.  The code run fines on the Galaxy S III (with Android 4) but is broken on the Galaxy Tab 2 7.7 running Android 3.2.  The code we are running is copied directly from the usage sample in the readme.

11-05 22:23:22.030: I/Web Console(14989): Received Event: deviceready at file:///android_asset/www/js/index.js:67
11-05 22:23:22.030: I/Web Console(14989): SQLitePlugin at file:///android_asset/www/js/SQLitePlugin.js:5
11-05 22:23:22.030: I/Web Console(14989): SQLitePlugin.prototype.open at file:///android_asset/www/js/SQLitePlugin.js:29
11-05 22:23:22.145: I/Web Console(14989): DB opened: Database at file:///android_asset/www/js/SQLitePlugin.js:13
11-05 22:23:22.145: I/Web Console(14989): SQLitePluginTransaction - this.trans_id:1352154202148000 at file:///android_asset/www/js/SQLitePlugin.js:63
11-05 22:23:22.145: I/Web Console(14989): SQLitePluginTransaction.prototype.executeSql at file:///android_asset/www/js/SQLitePlugin.js:143
11-05 22:23:22.145: I/Web Console(14989): success NULL:DROP TABLE IF EXISTS test_table at file:///android_asset/www/js/SQLitePlugin.js:170
11-05 22:23:22.145: I/Web Console(14989): executeSql - add_to_transactionDROP TABLE IF EXISTS test_table at file:///android_asset/www/js/SQLitePlugin.js:179
11-05 22:23:22.145: I/Web Console(14989): SQLitePluginTransaction.prototype.executeSql at file:///android_asset/www/js/SQLitePlugin.js:143
11-05 22:23:22.145: I/Web Console(14989): success NULL:CREATE TABLE IF NOT EXISTS test_table (id integer primary key, data text, data_num integer) at file:///android_asset/www/js/SQLitePlugin.js:170
11-05 22:23:22.145: I/Web Console(14989): executeSql - add_to_transactionCREATE TABLE IF NOT EXISTS test_table (id integer primary key, data text, data_num integer) at file:///android_asset/www/js/SQLitePlugin.js:179
11-05 22:23:22.145: I/Web Console(14989): SQLitePluginTransaction.prototype.executeSql at file:///android_asset/www/js/SQLitePlugin.js:143
11-05 22:23:22.145: I/Web Console(14989): success not null:INSERT INTO test_table (data, data_num) VALUES (?,?) at file:///android_asset/www/js/SQLitePlugin.js:150
11-05 22:23:22.150: I/Web Console(14989): executeSql - add_to_transactionINSERT INTO test_table (data, data_num) VALUES (?,?) at file:///android_asset/www/js/SQLitePlugin.js:179
11-05 22:23:22.150: I/Web Console(14989): SQLitePluginTransaction.prototype.complete at file:///android_asset/www/js/SQLitePlugin.js:183
11-05 22:23:22.150: E/SqliteCursor.cpp(14989): Invalid statement in fillWindow()
11-05 22:23:22.150: E/SqliteCursor.cpp(14989): Invalid statement in fillWindow()
11-05 22:23:22.150: W/System.err(14989): android.database.sqlite.SQLiteException: no such table: test_table: , while compiling: INSERT INTO test_table (data, data_num) VALUES (?,?)
11-05 22:23:22.150: W/System.err(14989):    at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
11-05 22:23:22.150: W/System.err(14989):    at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
11-05 22:23:22.150: W/System.err(14989):    at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:146)
11-05 22:23:22.150: W/System.err(14989):    at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:367)
11-05 22:23:22.150: W/System.err(14989):    at
...

**Comment by dust10** [comment]
We are using Cordova 2.1.0.  Cordova 2.2.0 had the same result.

**Comment by brody2consult** [comment]
Please try this in both Android 3.2 and Android 4.0 simulators and report the results.

**Comment by brody2consult** [comment]
Android version is now moved, if it is not working please raise in issue at: https://github.com/brodyspark/PhoneGap-sqlitePlugin-Android/issues
