### ISSUE TITLE
Problems retrieving data from db

### ISSUE THREAD

**Issue by morganestes** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#49]
I have an app that was originally written for PhoneGap 1.0.0 that was recently upgraded to 2.2.0 so I can use this plugin with SQLCipher. I'm having problems with a `SELECT` statement never returning results, even though I know there's data in there.

Here's the rundown:
- The database is created with the following code:

``` javascript
THDatabase.DatabaseConnection = sqlitePlugin.openDatabase(THDatabase.name, THDatabase.currentVersion, THDatabase.displayName, THDatabase.size);

THDatabase.DatabaseConnection.transaction(THDatabase.CreateUsersTable, THDatabase.FatalErrorCallback);
THDatabase.DatabaseConnection.transaction(THDatabase.CreateCentersTable, THDatabase.FatalErrorCallback);
...
```
- Once a user registers, the Centers and Users tables have data inserted.
- When the login screen loads, the db is queried for Centers and Users.

``` javascript
/* Centers */
    LoadCenters: function LoadCenters() {
        console.log("LoadCenters");
        THDatabase.DatabaseConnection.transaction(THDatabase.LoadCentersImpl, THDatabase.FatalErrorCallback);
        console.log('THDB.LoadCenters called from: ' + arguments.callee.caller.name);
    },
    LoadCentersImpl: function(tx) {
        console.log("Loading centers.");
        tx.executeSql('SELECT * FROM Centers', [], THDatabase.LoadCentersParse, THDatabase.RecoverableErrorCallback);
    },
    LoadCentersParse: function(tx, results) {
        console.log('parsing centers');
        var dataArray = [];
        var len = results.rows.length;
...
},
    /* Users */
    LoadUsers: function LoadUsers() {
        console.info("THDB.LoadUsers");
        THDatabase.DatabaseConnection.transaction(THDatabase.LoadUsersImpl, THDatabase.FatalErrorCallback);
    },

    LoadUsersImpl: function (tx) {
        console.info("Loading users...");
        tx.executeSql('SELECT * FROM Users', [], THDatabase.LoadUsersParse, THDatabase.RecoverableErrorCallback);
    },

    LoadUsersParse: function (tx, results) {
        console.info('parsing users...');
        var dataArray = [];
        var len = results.rows.length;
        console.log(len);
...
}
```

The problem I'm having is that Centers is loaded, but `THDatabase.LoadUsersParse()` never seems to get called. The console.log stops at "Loading users...". I'm still able to log into the app, but nothing else that requires reading from the db works.

Turning DEBUG on logs this right after "Loading users...":

``` console
SQLitePlugin.backgroundExecuteSqlBatch: {"executes":[{"query":["BEGIN"],"path":"ThinkHealthDBs.db","callback":"cb55"},{"query":["SELECT * FROM Users"],"path":"ThinkHealthDBs.db","callback":"cb56"}]}
```

This is a problem with and without SQLCipher being used.

**Comment by morganestes** [comment]
I've decided the most likely culprit is having multiple calls to the db from within scattered functions. They're not being executed sequentially (since JS is async), and they're so nested that eventually it just shuts down.

The readme says to "add application logic to break large batches into smaller batch transactions", but I can't find any examples of how to do that.

This was supposed to be just a drop-in replacement, but these same calls work without it. What's different and how can I get the "regular" WebSQL functionality working with this?

**Comment by brody2consult** [comment]
Please can you report which platform (iOS or Android) you are using and also how recent is your download of this plugin. Some changes were made recently to provide better support for nested transactions.

**Comment by brody2consult** [comment]
I took another look at the code that you pasted and this should be simple enough. Please make sure you try your code with the latest version of this plugin. If it still does not work for you, can you please make a more simple test program that can reproduce and demonstrate the problem you are having and make sure you report whether you are using iOS or Android version. You can also send the information to chris.brody@gmail.com

**Comment by brody2consult** [comment]
I did not hear anything for a few weeks and hereby close this issue. If you still see an issue:
- please make a very simple test program that can reproduce and demonstrate the problem.
- if it is for Android, please raise the issue here: https://github.com/brodyspark/PhoneGap-sqlitePlugin-Android/issues
