### ISSUE TITLE
How do I enforce foreign keys?

### ISSUE THREAD

**Issue by joemontana** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#50]
I tried running a query with 'PRAGMA foreign_keys = ON' from my app to set them on. No errors there. Then I opened the database via command line and checked foreign keys status and it was off. Am I doing something wrong?

**Comment by brody2consult** [comment]
First can you please report whether you are trying the iOS or Android
version. It would also help if can post a small test program if it can
help reproduce the problem. I expect to look at this issue on
Wednesday.

**Comment by joemontana** [comment]
I'm testing on iOS Simulator 4.3, sorry, I should've said that :P
I was also reading on other websites that even though foreign keys arent ON by default, sqlite will enforce matters with triggers. I have triggers on my DB anyway, so I'll double check if that works without foreign keys ON.

BTW, I added some logs in the plugin.m and I noticed executions run after a BEGIN command. On sqlite.org website it states that "This pragma is a no-op within a transaction; foreign key constraint enforcement may only be enabled or disabled when there is no pending BEGIN or SAVEPOINT." Maybe this could be affecting matters?

I zipped a simple project here: http://cl.ly/332x3x3S1D2B
cheers

**Comment by brody2consult** [comment]
> BTW, I added some logs in the plugin.m and I noticed executions run after a BEGIN command. On sqlite.org website it states that "This pragma is a no-op within a transaction; foreign key constraint enforcement may only be enabled or disabled when there is no pending BEGIN or SAVEPOINT." Maybe this could be affecting matters?

Yes it could be. For the iOS version ONLY, you can also call
executeSql() method directly on the DB object. This is documented in
README.md and as you may know is NOT compatible with the HTML5 SQL API
so I had documented this as obsolete. Please report whether or not
this can solve your issue; I will continue to support this method if
it solves the problem.

Chris

**Comment by brody2consult** [comment]
> Yes it could be. For the iOS version ONLY, you can also call
> executeSql() method directly on the DB object. This is documented in
> README.md and as you may know is NOT compatible with the HTML5 SQL API
> so I had documented this as obsolete. Please report whether or not
> this can solve your issue; I will continue to support this method if
> it solves the problem.

I had another idea to add a DB method such as executePragma() or
executePragmaStatement() to explicitly support PRAGMA statements on
the iOS version, instead of db.executeSql(). I still need to think
about it for a few days.

**Comment by brody2consult** [comment]
New executePragmaStatement() function has been added. This pragma is not always persistent in the database.

**Comment by PterPmnta** [comment]
```
CREATE TABLE IF NOT EXISTS CONTENT (id_content INTEGER PRIMARY
   KEY AUTOINCREMENT,id_page INTEGER, FOREIGN KEY(id_page) REFERENCES PAGE (id_page))
```
