### ISSUE TITLE
ReferenceError: Can't find variable : dbname

### ISSUE THREAD

**Issue by gaspard22** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#51]
Got this error using the examples from your zip, 
![Capture d e cran 2012-12-27 a 11 04 19](https://f.cloud.github.com/assets/3062285/32348/14d7d902-500e-11e2-84a6-23123b72b8d9.png)

using Xcode 4.5.2
cordova 2.2.0
the zip downloaded was the 21 december

**Comment by brody2consult** [comment]
I will look at the issue tonight.

Chris

**Comment by brody2consult** [comment]
A fix has been made, please report whether or not it works for you.

**Comment by gaspard22** [comment]
thanks everyting works fine, in your example, but now i tried with an example of mine , with sencha + phonegap and a
" DB opened: undefined  " message is log.

i have deleted "this" and your plugin works.
