### ISSUE TITLE
Plugin does not work on Samsung Galaxy Tab 2 with Android 3.2

### ISSUE THREAD

**Issue by renatovieira91** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#52]
We are hitting an issue where tables are not being created in the database created with the sqlite plugin. The code run fines on devices with Android 4 but is broken on the Galaxy Tab 2 7.7 running Android 3.2. The code we are running is copied directly from the usage sample in the readme.

11-05 22:23:22.030: I/Web Console(14989): Received Event: deviceready at file:///android_asset/www/js/index.js:67
11-05 22:23:22.030: I/Web Console(14989): SQLitePlugin at file:///android_asset/www/js/SQLitePlugin.js:5
11-05 22:23:22.030: I/Web Console(14989): SQLitePlugin.prototype.open at file:///android_asset/www/js/SQLitePlugin.js:29
11-05 22:23:22.145: I/Web Console(14989): DB opened: Database at file:///android_asset/www/js/SQLitePlugin.js:13
11-05 22:23:22.145: I/Web Console(14989): SQLitePluginTransaction - this.trans_id:1352154202148000 at file:///android_asset/www/js/SQLitePlugin.js:63
11-05 22:23:22.145: I/Web Console(14989): SQLitePluginTransaction.prototype.executeSql at file:///android_asset/www/js/SQLitePlugin.js:143
11-05 22:23:22.145: I/Web Console(14989): success NULL:DROP TABLE IF EXISTS test_table at file:///android_asset/www/js/SQLitePlugin.js:170
11-05 22:23:22.145: I/Web Console(14989): executeSql - add_to_transactionDROP TABLE IF EXISTS test_table at file:///android_asset/www/js/SQLitePlugin.js:179
11-05 22:23:22.145: I/Web Console(14989): SQLitePluginTransaction.prototype.executeSql at file:///android_asset/www/js/SQLitePlugin.js:143
11-05 22:23:22.145: I/Web Console(14989): success NULL:CREATE TABLE IF NOT EXISTS test_table (id integer primary key, data text, data_num integer) at file:///android_asset/www/js/SQLitePlugin.js:170
11-05 22:23:22.145: I/Web Console(14989): executeSql - add_to_transactionCREATE TABLE IF NOT EXISTS test_table (id integer primary key, data text, data_num integer) at file:///android_asset/www/js/SQLitePlugin.js:179
11-05 22:23:22.145: I/Web Console(14989): SQLitePluginTransaction.prototype.executeSql at file:///android_asset/www/js/SQLitePlugin.js:143
11-05 22:23:22.145: I/Web Console(14989): success not null:INSERT INTO test_table (data, data_num) VALUES (?,?) at file:///android_asset/www/js/SQLitePlugin.js:150
11-05 22:23:22.150: I/Web Console(14989): executeSql - add_to_transactionINSERT INTO test_table (data, data_num) VALUES (?,?) at file:///android_asset/www/js/SQLitePlugin.js:179
11-05 22:23:22.150: I/Web Console(14989): SQLitePluginTransaction.prototype.complete at file:///android_asset/www/js/SQLitePlugin.js:183
11-05 22:23:22.150: E/SqliteCursor.cpp(14989): Invalid statement in fillWindow()
11-05 22:23:22.150: E/SqliteCursor.cpp(14989): Invalid statement in fillWindow()
11-05 22:23:22.150: W/System.err(14989): android.database.sqlite.SQLiteException: no such table: test_table: , while compiling: INSERT INTO test_table (data, data_num) VALUES (?,?)
11-05 22:23:22.150: W/System.err(14989): at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
11-05 22:23:22.150: W/System.err(14989): at android.database.sqlite.SQLiteCompiledSql.(SQLiteCompiledSql.java:64)
11-05 22:23:22.150: W/System.err(14989): at android.database.sqlite.SQLiteProgram.compileSql(SQLiteProgram.java:146)
11-05 22:23:22.150: W/System.err(14989): at android.database.sqlite.SQLiteProgram.compileAndbindAllArgs(SQLiteProgram.java:367)
11-05 22:23:22.150: W/System.err(14989): at
...

Please, help me!

**Comment by brody2consult** [comment]
First, can you make sure you are testing with the latest version of the sqlite plugin from https://github.com/brodyspark/PhoneGap-SQLitePlugin-Android, on an Android 3.2 simulator as well as the Samsung device.

Also, make sure you are using at least Cordova 2.0, latest version (2.2) is preferred.

If you still see the problem, please confirm that you are using the latest version of the plugin, which version of Cordova you are using, and I prefer you raise the issue for the Android version at: https://github.com/brodyspark/PhoneGap-SQLitePlugin-Android/issues

Thanks,
Chris
