### ISSUE TITLE
Building on ios for armv7s architecture 

### ISSUE THREAD

**Issue by rahulteotia** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#53]
We tried to build the plugin along with SQLCipher for armv7s architecture but facing this problem

ld: warning: ignoring file /Users/User/Library/Developer/Xcode/DerivedData/MobileTest-dacraqaybebsbwacvbwytgqneaoa/Build/Products/Debug-iphoneos/libCordova.a, file was built for archive which is not the architecture being linked (armv7s): /Users/User/Library/Developer/Xcode/DerivedData/MobileTest-dacraqaybebsbwacvbwytgqneaoa/Build/Products/Debug-iphoneos/libCordova.a
Undefined symbols for architecture armv7s:
  "_OBJC_CLASS_$_CDVPlugin", referenced from:
      _OBJC_CLASS_$_SQLitePlugin in SQLitePlugin.o
  "_OBJC_CLASS_$_CDVViewController", referenced from:
      _OBJC_CLASS_$_MainViewController in MainViewController.o
  "_OBJC_METACLASS_$_CDVPlugin", referenced from:
      _OBJC_METACLASS_$_SQLitePlugin in SQLitePlugin.o
  "_OBJC_METACLASS_$_CDVViewController", referenced from:
      _OBJC_METACLASS_$_MainViewController in MainViewController.o

**Comment by brody2consult** [comment]
From the warning/error messages, it seems pretty clear that your Cordova
build does not support the armv7s architecture. Please make sure you try
this with the latest release of Cordova (2.3) and try this with a simpler
plugin such as the DatePicker. You may have to rebuild the Cordova library
itself to support armv7s. Please raise this as an issue on the Cordova
project if its build does not work for armv7s.

Chris

**Comment by rahulteotia** [comment]
Thanks chris

Our project is using Cordova 2.2, and the build setting is now set to support all architecture armv7 and 7s both. The build settings are same for all the three project (main, openssl 7 sqlcipher) now and its building fine

**Comment by vedatsivri** [comment]
Hello Rahul

I'm using cordova 2.5 with Xcode 5 but still getting link error. is there any special configuration needed on Xcode or cordova ? 

Thanks
Vedat Sivri

**Comment by rahulteotia** [comment]
Hi Vedat, While building which of the project is giving you this error? Cordova or your main project?

**Comment by vedatsivri** [comment]
Hi Rahul,

I was getting error on main project. I think it was link error that depends on architecture.
So when i changed arm configuration from armv7s to standart form build settings then fixed. Now it is working fine. 

Thank you so much for response.

Vedat Sivri
