### ISSUE TITLE
Update query not working on iOS with phonegap 2.3

### ISSUE THREAD

**Issue by nikhilr57** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#55]
Hi,
It was working on phonegap 2.2.
But it is not working as it is on 2.3.
After seeing console, it shows that "DB opened: undefined"

Please suggest/update.

regards,

**Comment by brody2consult** [comment]
I am recovering from some sickness and can take a look in 1-2 weeks.

Chris

**Comment by nikhilr57** [comment]
@Chris, The issue is solved.. It turned out to be some issue with database copy code in android. Works fine now. Sorry for time.
Take care :)
