### ISSUE TITLE
DB opened: undefined

### ISSUE THREAD

**Issue by camdagr8** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#56]
When opening a db the javascript logs an undefined value for db. 

This can be fixed at line 63 of the SQLitePlugin.js file by using  console.log("DB opened: " + dbargs.name); instead of console.log("DB opened: " + this.dbname);
'this' is out of scope when used inside the function ().

**Comment by brody2consult** [comment]
This version is no longer supported.
