### ISSUE TITLE
Removal of JSONKit from Cordova 2.4.0

### ISSUE THREAD

**Issue by ghost** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#58]
As mentioned below, JSONKit has been removed from Cordova. It was replaced with NSJSONSerialiation.

CODE:
[self respond:callback withString:[resultSet NSJSONSerialization] withType:@"success"];

ERROR:
[__NSDictionaryM cdvjk_JSONString]: unrecognized selector sent to instance 0x9b74bc0

http://shazronatadobe.wordpress.com/2013/02/08/whats-new-in-cordova-ios-2-4-0/

**Comment by jthurston** [comment]
Does replacing CORDOVA/JSONKit.h with CORDOVA/CDVJSON.h in SQLitePlugin.h fix the issue?

**Comment by ujwalanandyala** [comment]
I have similar issue with SQLite plugin on ios 6.1 using cordova 2.5.0. Replacing CORDOVA/JSONKit.h with CORDOVA/CDVJSON.h didn't help.

Please let me know if anyone has a solution

**Comment by kriscarle** [comment]
It is working for me on iOS 6.1 + Cordova 2.5.0  There is one other change you need to make in SQLitePlugin.m  It is in my pull request https://github.com/brodyspark/PhoneGap-SQLitePlugin-iOS/pull/60/files

**Comment by ujwalanandyala** [comment]
that worked. Thank You!

**Comment by cmamishra** [comment]
thanks it worked!
