### ISSUE TITLE
Uniform plugin Javascript

### ISSUE THREAD

**Issue by brody2consult** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#6]
Cordova 1.6 has made the same Javascript (cordova-xxx.js) for Android and iOS. It would be nice to keep the same Javascript for the SQLitePlugin also for Android and iOS. This fix is depending on [#5](https://github.com/chbrody/Cordova-SQLitePlugin/issues/5).

**Comment by brody2consult** [comment]
Comment from @marcucio on #5: iOS already handles batches. iOS is actually faster than Android even with my changes but I don't think my version can be optimized any further.

It will be a challenge to bring the plugin Javascript into sync if the iOS and Android do not handle batches the same way. Hopefully we can get the differences to a minimum on the Javascript side.

**Comment by brody2consult** [comment]
Also, I leave it up to discussion whether to continue based on CoffeeScript or Javascript source. The CoffeeScript version is easier to author and adapt to major changes but it becomes a challenge for maintenance in the user community.

**Comment by marcucio** [comment]
i'm a purist, I vote to have just a JS version. More people can contribute to the js version than can the .coffee version.

**Comment by brody2consult** [comment]
> i'm a purist, I vote to have just a JS version. More people can contribute to the js version than can the .coffee version.
> +1

**Comment by marcucio** [comment]
Chris, I was thinking of deleting my version of the plugin and just branching off of yours. Let me know if you think there would be a problem with me doing this (you seems to be more versed in github than I)

Your code seems the most up to date the only thing that I think should be changed is the name of Cordova-iOS should probably just be iOS (but I can get over this :)

**Comment by brody2consult** [comment]
Mike that sounds like a good idea, I did fork off your repository but did nothing with it. I have been able to merge the branches together by some magic. I think you especially will have to delete your old fork of Phonegap-SQLitePlugin if you want to fork off my repository. And I did go ahead to rename Cordova-iOS to iOS.

**Comment by brody2consult** [comment]
Going forward, I still want to keep the CoffeeScript to make it easier for myself until we really get this resolved. I will make the JS version leading but you may see some massive changes due to my own regeneration from CoffeeScript. I want to simplify the object prototyping and I think it will be easier for me to do this in CoffeeScript.

**Comment by marcucio** [comment]
FYI, I upgraded to cordova 1.6 because of the localstorage bug fix, I won't be testing or using the old version any more.

**Comment by brody2consult** [comment]
Very smart, I just wrote a shim in case people have old PhoneGap plugins: https://github.com/chbrody/Cordova-PGPluginShim

I think I will go ahead, delete the old PG version and start cleaning up the Javascript.

**Comment by brody2consult** [comment]
The internal Cordova/PhoneGap interface between the Android and iOS versions are so different that I do not expect to fix this one.
