### ISSUE TITLE
Error with Cordova 2.7

### ISSUE THREAD

**Issue by elcreativo** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#63]
Hello Phonegap Experts,

We have updated our iOS app to Cordova 2.7. Now we get an error message when using the "PhoneGap iOS SQLitePlugin (brodyspark / latest version)".

The old format of this exec call has been removed (deprecated since 2.1). Change to:

cordova.exec (null, null, "SQLitePlugin," open ", [{" name ":" dbname "," callback ":" cb1 "}]);
We have tried to fix the error. But had no success. Does anyone have an answer what we should do?

Best regards

**Comment by brody2consult** [comment]
The plugin needs to be updated for 2.5+. I have not had much time to work
on this and do not guarantee when.

Chris Brody

**Comment by j3k0** [comment]
I updated the plugin for 2.5+ on my fork:
https://github.com/j3k0/PhoneGap-SQLitePlugin-iOS

Needs to be tested more, but probably worth pulling once validated.

**Comment by brody2consult** [comment]
Please submit a pull request once you are reasonably confident in the
changes. Thanks Chris

On Friday, May 3, 2013, Jean-Christophe Hoelt wrote:

> I updated the plugin for 2.5+ on my fork:
> https://github.com/j3k0/PhoneGap-SQLitePlugin-iOS
> 
> Needs to be tested more, but probably worth pulling once validated.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brodyspark/PhoneGap-SQLitePlugin-iOS/issues/63#issuecomment-17391328
> .

## 

Sent from my mobile
